### ISSUE TITLE
移除插件後通知仍為秘書艦語音

### ISSUE THREAD

**Issue by louisau2011** [poooi/plugin-secretary#2]
你好，
我在移除插件后通知音效仍是舰娘的语音（可是不会随更换秘书舰而改变）
请问能如何解决...

我的移除方式如下：
1.从插件中重新设置通知声音
2.poi设定中禁用插件
3.关闭poi
4.移除插件目录
5.重启poi

我是使用osx版本的。

**Comment by yukixz** [comment]
hmm... 没考虑过删除插件的情况= =

这个插件是通过、自动设置 poi 本体的通知设置、来实现自定义通知音的。

如果想重置通知音为 poi 原本的通知音的话，
请打开「开发者工具」、切换到「Console」、然后输入并执行以下语句：
`var t=['construction','repair','expedition','morale'];for(i in t){config.set("poi.notify."+t[i]+".audio")}`

不需要再安装插件。

**Comment by louisau2011** [comment]
因为看见貌似是直接跟伺服器拿语音资源
个人胆小怕被封所以不太敢使用...

已经成功移除了，感谢
