### ISSUE TITLE
回复不到初始的 poi

### ISSUE THREAD

**Issue by KagamiChan** [poooi/plugin-secretary#4]
看了一下代码，没有回复到初始的 poi 的方法？难不成需要手动改 config.cson

**Comment by yukixz** [comment]
嗯、没有。因为懒得写。
需要清除设置请看这里：https://github.com/poooi/plugin-secretary/issues/2#issuecomment-159280233

**Comment by KagamiChan** [comment]
好吧，有时间我来个 pr = =

**Comment by yukixz** [comment]
哇！太好了！
